name: sharestapp
description: I'll make it Simple

#  * @author Prince Sanjivy, Vignesh Hendrix

# Sharestapp is an open source application that let's an end user to directly share an 
# image/video from Instagram to other apps in an exact image/video format, and 
# also allows the user to save in mobile's local storage.

# Have you ever felt disappointed that you can't share or save your Instagram's news feed 
# images to other apps or to your mobile's local storage directly in an exact image format?
# Of course yes,if your an Instagram user. That's the reason we made our "Sharestapp".  
# Sharestapp is an Open Source application (which will be available for free to every end users
# or Clients) that let's you to directly share an image that you liked, from Instagram and gives
# you an opportunity to share that image to other applications in your mobile,Save to your local
# storage,and yes ,if your a whatsapp user it also gives you a chance to directly upload that image
# as your whatsapp status and also share to your whatsapp contacts. Sharestapp will make your task
# simple and easier.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  receive_sharing_intent: ^1.4.1
  google_fonts: ^1.1.1
  http: ^0.12.2
  flutter_cache_manager: ^2.0.0
  image: ^2.1.18
  url_launcher: 

# dev_dependencies:
#   flutter_test:
#     sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/vignesh.jpeg
    - assets/sanjivy.jpg
